/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Participant = IDL.Record({
  'name' : IDL.Text,
  'sesaId' : IDL.Text,
  'registeredAt' : IDL.Int,
});
export const Submission = IDL.Record({
  'name' : IDL.Text,
  'boardState' : IDL.Vec(IDL.Nat),
  'submittedAt' : IDL.Int,
  'isCorrect' : IDL.Bool,
  'sesaId' : IDL.Text,
  'timeTakenSeconds' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClues' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getParticipants' : IDL.Func([], [IDL.Vec(Participant)], ['query']),
  'getSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasSubmitted' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isRegistered' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'registerParticipant' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitPuzzle' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat), IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Participant = IDL.Record({
    'name' : IDL.Text,
    'sesaId' : IDL.Text,
    'registeredAt' : IDL.Int,
  });
  const Submission = IDL.Record({
    'name' : IDL.Text,
    'boardState' : IDL.Vec(IDL.Nat),
    'submittedAt' : IDL.Int,
    'isCorrect' : IDL.Bool,
    'sesaId' : IDL.Text,
    'timeTakenSeconds' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClues' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getParticipants' : IDL.Func([], [IDL.Vec(Participant)], ['query']),
    'getSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasSubmitted' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isRegistered' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'registerParticipant' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitPuzzle' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat), IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };